# Astra information
client_id: ""
client_secret: ""
secure_connect_bundle_path: ""
keyspace: ""

# Logging 
log_level: ""

# OpenAI
openai_api_key: ""
openai_model: "gpt-4-turbo-preview"
model_system_role: "You are an Apache Cassandra expert at data modeling and Generative AI strategy."
